# Generated by Django 5.0.6 on 2024-05-09 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aged', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AFostVerificatAzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiredOferedStock', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Verificare prin data',
            },
        ),
        migrations.CreateModel(
            name='CheckIfFileWasAlreadyUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creare_fisier', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Date creare fisier Aged Stock',
            },
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_service_rep', models.CharField(max_length=100)),
                ('c_serv_status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Inactive', 'Inactive')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Customer service reps',
            },
        ),
        migrations.CreateModel(
            name='LocationsForStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_of_stocks', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Stock location',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Material types (chocolate, nuts, etc)',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_number', models.IntegerField()),
                ('customer_status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Inactive', 'Inactive')], max_length=10)),
                ('salesperson_owning_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('allocated_customer_service_rep', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aged.customerservice')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='AvailableStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('batch', models.CharField(max_length=100)),
                ('original_quantity_in_kg', models.IntegerField()),
                ('under_offer_quantity_in_kg', models.IntegerField(default=0)),
                ('sold_quantity_in_kg', models.IntegerField(default=0)),
                ('available_quantity_in_kg', models.IntegerField()),
                ('stock_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aged.locationsforstocks')),
            ],
            options={
                'verbose_name_plural': 'Available stock',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_material', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('product_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aged.brands')),
                ('product_material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aged.materialtype')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OffersLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_sold_or_declined_quantity_kg', models.IntegerField()),
                ('offer_status', models.CharField(choices=[('Offered', 'Offered'), ('Declined', 'Declined'), ('Sold', 'Sold'), ('Offer Expired', 'Offer Expired')], max_length=20)),
                ('discount_offered_percents', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_kg_offered', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_of_offer', models.DateField()),
                ('expiration_date_of_offer', models.DateField(blank=True, null=True)),
                ('date_of_outcome', models.DateField(blank=True, null=True)),
                ('stock_expired', models.BooleanField(default=False)),
                ('customer_that_received_offer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aged.customers')),
                ('offered_stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aged.availablestock')),
                ('sales_rep_that_made_the_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offered_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aged.products')),
            ],
            options={
                'verbose_name_plural': 'Offers log',
            },
        ),
        migrations.AddField(
            model_name='availablestock',
            name='available_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aged.products'),
        ),
    ]
